image: gitpod/workspace-base

tasks:
  - name: install mamba
    init: |
      curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
      bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
      /workspace/conda/bin/mamba init bash
      source ${HOME}/.bashrc
      mkdir -p /workspace/bin
      
      # set up conda evironment with R and needed packages
      mamba create -n gs -c conda-forge r-base r-argparse r-minpack.lm -y
      mamba activate gs
      mamba install -c bioconda kmc -y

      # install genomescope2 (both package and executible script)
      git clone https://github.com/tbenavi1/genomescope2.0
      R -e 'install.packages("genomescope2.0", repos=NULL, type="source")'
      install -c genomescope2.0/genomescope.R /workspace/bin

      # install genomeTelescope R package
      git clone https://github.com/KamilSJaron/GenomeTelescope
      R -e 'install.packages("GenomeTelescope", repos=NULL, type="source")'

      # download yeast data
      mkdir -p data && wget -P data ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR326/001/SRR3265401/SRR3265401_[12].fastq.gz
    command: |
      /workspace/conda/bin/mamba init bash
      source ${HOME}/.bashrc
      mamba activate gs

      export PATH=/workspace/bin:"$PATH"

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
